### ISSUE TITLE
Calculator not updated

### ISSUE THREAD

**Issue by Pohli** [Sikarjan/harbour-exrates#14]
Just now I used ExRates again after one month. So I updated rates several times and also switched the source. The rates list got updated correctly but the result field still shows me the rate from last month.

Jolla Phone with SFOS 3.0.1.11 and ExRates 1.4

**Comment by Sikarjan** [comment]
Thanks for reporting this. I can confirm the bug and will try to fix it within a week.

**Comment by Sikarjan** [comment]
Fixed the issue in version 1.5
