### ISSUE TITLE
App symbol covers rates on app cover if using light ambience

### ISSUE THREAD

**Issue by Pohli** [Sikarjan/harbour-exrates#15]
See title.

**Comment by Sikarjan** [comment]
I will redo the background image at some point, when I have a better idea for it.

**Comment by Sikarjan** [comment]
Sorry I list track of this. Could you please help me understanding what the issue is? I am not able to recreate the issue with the current version.

**Comment by Pohli** [comment]
I am also not able to reproduce the issue on my Xperia 10 III with SFOS 4.5.0.24. The issue is more than 4 years old and that time I had an Jolla Phone with SFOS 3.0.something. I close this one.
