### ISSUE TITLE
Clear sum text fields after base currency change

### ISSUE THREAD

**Issue by Pohli** [Sikarjan/harbour-exrates#17]
Example: Base currency is € and I enter a sum to convert to INR. Then I change the base currency to CHF. Now the calculation from € to INR is still shown but from just looking at the current page it seems that the calculation means CHF to INR.
So either clear the calculation after a base currency change or somehow indicate the previous base currency at the calculation.

**Comment by Sikarjan** [comment]
Result is updated when a new base currency is selected.
Fixed in version 1.6
