### ISSUE TITLE
BGN, HRK: flag and name missing in currency list

### ISSUE THREAD

**Issue by Pohli** [Sikarjan/harbour-exrates#4]
See title. I can attach screenshot if needed.

**Comment by Sikarjan** [comment]
I am sorry but the API I am currently using, a free one, does not provide rates for those currencies. I hope that I can integrate other sources with more currencies in the future.

**Comment by Pohli** [comment]
But the two rates are actually shown (correctly or not, didn't check), only the flags and the full currency names are missing.

**Comment by Sikarjan** [comment]
You are right. They must have been added to the currencies available. I will add them with the next revision.

**Comment by Sikarjan** [comment]
Name and flags added in version 0.3
